server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import:
      - "application-prod.yml"
      - "application-qa.yml"

loans:
  message: "Loans detail fetched from local APIs"
  contactDetails:
    name: "Robert Developer"
    email: "trangbn580@gmail.com"
  onCallSupport:
    - (555)123-345
    - (555)123-346